/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as DifferenceRouteImport } from './routes/difference'
import { Route as CountdownRouteImport } from './routes/countdown'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountriesCountryRouteImport } from './routes/countries.$country'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const DifferenceRoute = DifferenceRouteImport.update({
  id: '/difference',
  path: '/difference',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownRoute = CountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryRoute = CountriesCountryRouteImport.update({
  id: '/countries/$country',
  path: '/countries/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/difference': typeof DifferenceRoute
  '/holidays': typeof HolidaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$city': typeof CitiesCityRoute
  '/countries/$country': typeof CountriesCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/difference': typeof DifferenceRoute
  '/holidays': typeof HolidaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$city': typeof CitiesCityRoute
  '/countries/$country': typeof CountriesCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/difference': typeof DifferenceRoute
  '/holidays': typeof HolidaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$city': typeof CitiesCityRoute
  '/countries/$country': typeof CountriesCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countdown'
    | '/difference'
    | '/holidays'
    | '/sitemap.xml'
    | '/cities/$city'
    | '/countries/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countdown'
    | '/difference'
    | '/holidays'
    | '/sitemap.xml'
    | '/cities/$city'
    | '/countries/$country'
  id:
    | '__root__'
    | '/'
    | '/countdown'
    | '/difference'
    | '/holidays'
    | '/sitemap.xml'
    | '/cities/$city'
    | '/countries/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountdownRoute: typeof CountdownRoute
  DifferenceRoute: typeof DifferenceRoute
  HolidaysRoute: typeof HolidaysRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CitiesCityRoute: typeof CitiesCityRoute
  CountriesCountryRoute: typeof CountriesCountryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/difference': {
      id: '/difference'
      path: '/difference'
      fullPath: '/difference'
      preLoaderRoute: typeof DifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdown': {
      id: '/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof CountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$country': {
      id: '/countries/$country'
      path: '/countries/$country'
      fullPath: '/countries/$country'
      preLoaderRoute: typeof CountriesCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountdownRoute: CountdownRoute,
  DifferenceRoute: DifferenceRoute,
  HolidaysRoute: HolidaysRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CitiesCityRoute: CitiesCityRoute,
  CountriesCountryRoute: CountriesCountryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
